In [3]:
import torch


In [11]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [12]:
#Create tensor in pytorch
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-2.3331e+36,  4.5688e-41,  1.4000e-26],
        [ 3.0702e-41,  4.4842e-44,  0.0000e+00]])


In [15]:
#Create a filled tensor
describe(torch.zeros(2,3))
x = torch.ones(2,3)
describe(x)
x.fill_(6)
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[6., 6., 6.],
        [6., 6., 6.]])


In [16]:
#Create tensors from lists
x = torch.Tensor([[10,20,25],
                 [15,25,35]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[10., 20., 25.],
        [15., 25., 35.]])


In [17]:
#Create tensor from numpy
import numpy as np
npy_x = np.random.rand(3,4)
describe(torch.from_numpy(npy_x))

Type: torch.DoubleTensor
Shape/Size: torch.Size([3, 4])
Values: 
tensor([[0.7456, 0.2499, 0.7549, 0.9850],
        [0.1367, 0.8372, 0.8085, 0.1441],
        [0.0823, 0.3786, 0.2179, 0.9423]], dtype=torch.float64)


In [20]:
#Indexing & Slicing
x= torch.arange(12).view(3,4)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([3, 4])
Values: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [23]:
describe(x[:1,:3])

Type: torch.LongTensor
Shape/Size: torch.Size([1, 3])
Values: 
tensor([[0, 1, 2]])


In [25]:
describe(x[1,2])

Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
6


In [29]:
#Accessing Non continious locations of a tensor
ind = torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index=ind))

Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])


In [30]:
print(torch.cuda.is_available())

False
